import { DEFAULT_CONFIG, generate, type Config } from './mikrotik';

export interface DVlan {
  id: number;
  name: string;
  /** May this VLAN reach the internet through the router? */
  internet: boolean;
}

export interface Design {
  vlans: DVlan[];
  /** Access port -> VLAN id, or null when unused. */
  access: Record<string, number | null>;
  /** Directional policy: `${from}>${to}` is true when `from` may start connections to `to`. */
  allow: Record<string, boolean>;
  mgmtVlan: number;
}

export const SWITCH_PORTS = Array.from({ length: 16 }, (_, i) => `ether${i + 1}`);
export const SWITCH_TRUNK = 'sfp-sfpplus1';
export const ROUTER_WAN = 'ether1';
export const ROUTER_TRUNK = 'ether2';

export const pairKey = (from: number, to: number) => `${from}>${to}`;

/** One /24 per VLAN, unique for every ID 1-4094: 10.<id/256>.<id%256>.0/24 */
export const subnetOf = (id: number) => `10.${id >> 8}.${id & 255}.0/24`;
export const gatewayOf = (id: number) => `10.${id >> 8}.${id & 255}.1`;
export const switchAddrOf = (id: number) => `10.${id >> 8}.${id & 255}.2`;
export const vlanIface = (v: DVlan) => `vlan${v.id}-${v.name}`;

export function defaultDesign(): Design {
  const access: Record<string, number | null> = {};
  SWITCH_PORTS.forEach((p, i) => {
    access[p] = i < 4 ? 10 : i < 8 ? 20 : i < 10 ? 30 : i === 15 ? 99 : null;
  });
  return {
    vlans: [
      { id: 10, name: 'staff', internet: true },
      { id: 20, name: 'guest', internet: true },
      { id: 30, name: 'servers', internet: false },
      { id: 99, name: 'mgmt', internet: false },
    ],
    access,
    allow: { [pairKey(10, 30)]: true, [pairKey(99, 10)]: true, [pairKey(99, 20)]: true, [pairKey(99, 30)]: true },
    mgmtVlan: 99,
  };
}

const NAME = /^[A-Za-z0-9_-]{1,16}$/;

export function validateDesign(d: Design): string[] {
  const errors: string[] = [];
  if (d.vlans.length === 0) errors.push('Add at least one VLAN.');
  const ids = new Set<number>();
  const names = new Set<string>();
  for (const v of d.vlans) {
    if (!Number.isInteger(v.id) || v.id < 1 || v.id > 4094) errors.push(`VLAN ID ${v.id} must be 1-4094.`);
    if (ids.has(v.id)) errors.push(`VLAN ${v.id} is listed twice.`);
    ids.add(v.id);
    if (!NAME.test(v.name)) errors.push(`VLAN ${v.id}: name must be 1-16 letters, digits, _ or -.`);
    if (names.has(v.name)) errors.push(`VLAN name "${v.name}" is used twice.`);
    names.add(v.name);
  }
  if (!ids.has(d.mgmtVlan)) errors.push('Pick a management VLAN from the list.');
  for (const [port, id] of Object.entries(d.access)) {
    if (id !== null && !ids.has(id)) errors.push(`${port} is assigned to VLAN ${id}, which does not exist.`);
  }
  return errors;
}

export function accessPorts(d: Design, vlanId: number): string[] {
  return SWITCH_PORTS.filter((p) => d.access[p] === vlanId);
}

/** RouterOS script for the switch, built on the tested config generator. */
export function generateSwitch(d: Design): { rsc: string; errors: string[] } {
  const errors = validateDesign(d);
  if (errors.length) return { rsc: '', errors };
  const cfg: Config = {
    ...DEFAULT_CONFIG,
    role: 'vlan-switch',
    deviceId: 'crs326',
    identity: 'sw-access-01',
    trunkPort: SWITCH_TRUNK,
    mgmtVlanId: d.mgmtVlan,
    mgmtCidr: `${switchAddrOf(d.mgmtVlan)}/24`,
    mgmtGateway: gatewayOf(d.mgmtVlan),
    vlans: d.vlans.map((v) => ({ id: v.id, name: v.name, ports: accessPorts(d, v.id) })),
  };
  return generate(cfg);
}

/** RouterOS script for the router-on-a-stick that routes and filters between the VLANs. */
export function generateRouter(d: Design): { rsc: string; errors: string[] } {
  const errors = validateDesign(d);
  if (errors.length) return { rsc: '', errors };
  const L: string[] = [
    '# r1 - router on a stick for the VLAN design',
    '# Generated by Network Academy. Target: RouterOS v7.',
    '# Review every line and test in a lab before applying to production.',
    '',
    '/system identity set name=r1',
    '',
    '# --- Interface lists ---',
    '/interface list add name=WAN',
    '/interface list add name=LAN',
    `/interface list member add list=WAN interface=${ROUTER_WAN}`,
    '',
    `# --- One VLAN interface per VLAN, all riding on ${ROUTER_TRUNK} ---`,
  ];
  for (const v of d.vlans) {
    const n = vlanIface(v);
    L.push(`/interface vlan add name=${n} interface=${ROUTER_TRUNK} vlan-id=${v.id}`);
    L.push(`/interface list member add list=LAN interface=${n}`);
    L.push(`/ip address add address=${gatewayOf(v.id)}/24 interface=${n}`);
  }
  L.push('', '# --- DHCP per VLAN ---');
  for (const v of d.vlans) {
    const n = vlanIface(v);
    const net = subnetOf(v.id).replace('.0/24', '');
    L.push(`/ip pool add name=pool-${v.name} ranges=${net}.10-${net}.254`);
    L.push(`/ip dhcp-server add name=dhcp-${v.name} interface=${n} address-pool=pool-${v.name} lease-time=1h disabled=no`);
    L.push(`/ip dhcp-server network add address=${subnetOf(v.id)} gateway=${gatewayOf(v.id)} dns-server=${gatewayOf(v.id)}`);
  }
  const mgmt = d.vlans.find((v) => v.id === d.mgmtVlan)!;
  L.push(
    '',
    '# --- WAN and DNS ---',
    `/ip dhcp-client add interface=${ROUTER_WAN} disabled=no`,
    '/ip dns set allow-remote-requests=yes servers=1.1.1.1,9.9.9.9',
    '/ip firewall nat add chain=srcnat action=masquerade out-interface-list=WAN comment="masquerade to WAN"',
    '',
    '# --- Firewall: protect the router ---',
    '/ip firewall filter add chain=input action=accept connection-state=established,related,untracked comment="accept established"',
    '/ip firewall filter add chain=input action=drop connection-state=invalid comment="drop invalid"',
    '/ip firewall filter add chain=input action=accept protocol=icmp comment="accept ICMP"',
    '/ip firewall filter add chain=input action=accept in-interface-list=LAN protocol=udp dst-port=53,67 comment="DNS and DHCP from every VLAN"',
    '/ip firewall filter add chain=input action=accept in-interface-list=LAN protocol=tcp dst-port=53 comment="DNS over TCP"',
    `/ip firewall filter add chain=input action=accept in-interface=${vlanIface(mgmt)} comment="management VLAN may manage the router"`,
    '/ip firewall filter add chain=input action=drop comment="drop everything else"',
    '',
    '# --- Firewall: policy between VLANs ---',
    '/ip firewall filter add chain=forward action=accept connection-state=established,related,untracked comment="accept established"',
    '/ip firewall filter add chain=forward action=drop connection-state=invalid comment="drop invalid"',
  );
  for (const a of d.vlans) {
    for (const b of d.vlans) {
      if (a.id !== b.id && d.allow[pairKey(a.id, b.id)]) {
        L.push(`/ip firewall filter add chain=forward action=accept in-interface=${vlanIface(a)} out-interface=${vlanIface(b)} comment="${a.name} may reach ${b.name}"`);
      }
    }
  }
  for (const v of d.vlans) {
    if (v.internet) L.push(`/ip firewall filter add chain=forward action=accept in-interface=${vlanIface(v)} out-interface-list=WAN comment="${v.name} may use the internet"`);
  }
  L.push('/ip firewall filter add chain=forward action=drop comment="isolate everything else"', '');
  return { rsc: L.join('\n'), errors: [] };
}

export interface Trace {
  ok: boolean;
  steps: string[];
}

const nameOf = (d: Design, id: number) => d.vlans.find((v) => v.id === id)?.name ?? String(id);

/** Explain what happens to a ping from one switch port to another port, or to the internet. */
export function trace(d: Design, from: string, to: string | 'internet'): Trace {
  const a = d.access[from] ?? null;
  if (a === null) return { ok: false, steps: [`${from} has no VLAN, so frames from it are dropped. Assign it to a VLAN first.`] };
  const av = nameOf(d, a);
  const up = [
    `${from} is an access port in VLAN ${a} (${av}). The switch tags frames with VLAN ${a}.`,
  ];
  if (to === 'internet') {
    const v = d.vlans.find((x) => x.id === a)!;
    const steps = [...up, `The switch sends the tagged frame up the trunk (${SWITCH_TRUNK}) to the router.`, `The router receives it on ${vlanIface(v)}, and routes it towards the internet.`];
    if (!v.internet) return { ok: false, steps: [...steps, `No firewall rule lets ${av} use the internet. The final rule drops it.`] };
    return { ok: true, steps: [...steps, `The rule "${av} may use the internet" accepts it, and NAT rewrites the source address.`] };
  }
  const b = d.access[to] ?? null;
  if (b === null) return { ok: false, steps: [...up, `${to} has no VLAN, so the frame never reaches a host.`] };
  const bv = nameOf(d, b);
  if (from === to) return { ok: true, steps: ['That is the same port.'] };
  if (a === b) {
    return { ok: true, steps: [...up, `${to} is in the same VLAN, so the switch forwards the frame directly. It never reaches the router, and no firewall rule applies.`] };
  }
  const steps = [
    ...up,
    `${to} is in VLAN ${b} (${bv}): a different Layer 2 network, so the frame must go through the router.`,
    `The trunk carries it to the router's ${vlanIface(d.vlans.find((x) => x.id === a)!)} interface.`,
  ];
  if (!d.allow[pairKey(a, b)]) {
    return { ok: false, steps: [...steps, `The router looks for a rule allowing ${av} to ${bv}. There is none, so the final rule drops it.`] };
  }
  return {
    ok: true,
    steps: [
      ...steps,
      `The rule "${av} may reach ${bv}" accepts it. The router forwards it out of ${vlanIface(d.vlans.find((x) => x.id === b)!)}.`,
      `The switch removes the tag and delivers the frame to ${to}. Replies are allowed as established traffic.`,
    ],
  };
}
